name: CI - Code

on:
  workflow_dispatch:
  pull_request:
    paths:
    - .github/workflows/ci.yml
    - src/**

env:
  dotnetVersion: '6.0.x'

jobs:
  verify_codebase:
    name: Verify Codebase
    runs-on: ubuntu-latest
    steps:
        # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

        # Install .NET
      - name: Install .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.dotnetVersion }}

        # Build Solution
      - name: Build Solution
        run: dotnet build src/MigrationTool.sln --configuration release
